#!/bin/sh
set -e

case "$1" in
    remove|purge)
        # Reload udev rules
        if [ -x "$(command -v udevadm)" ]; then
            udevadm control --reload-rules || true
            udevadm trigger --subsystem-match=tty || true
        fi

        # Update desktop database
        if [ -x "$(command -v update-desktop-database)" ]; then
            update-desktop-database -q /usr/share/applications || true
        fi

        # Update icon cache
        if [ -x "$(command -v gtk-update-icon-cache)" ]; then
            gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
        fi
    ;;
esac

exit 0
