name: Build Baudix

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - 'docs/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - 'docs/**'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.3'
          modules: 'qtserialport'

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential libgl1-mesa-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release
