name: Build Baudix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          modules: 'qtserialport qtwebsockets'
        if: matrix.os == 'windows-latest'

      - name: Install Qt (Ubuntu)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
          modules: 'qtserialport qtwebsockets'
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-sync1 libxcb-xfixes0-dev libxcb-xinerama0 libxcb-shm0 libxcb-xkb1 libxcb-render0-dev libxcb1-dev libx11-xcb-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        run: |
          cd build
          cmake --build . --config Release
